kind = "web"
previewPath = "/"
title = "Vaultalk"
version = "1.0.0"
id = "artifacts/vaultalk"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25368

[services.development]
run = "pnpm --filter @workspace/vaultalk run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/vaultalk", "run", "build" ]
publicDir = "artifacts/vaultalk/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25368"
BASE_PATH = "/"
