uploads = []

[[generated]]
id = "rv2c7Xl0hWGzCIYfbzo-K"
uri = "file://artifacts/mockup-sandbox/public/images/bg-tech-1.png"
type = "image"
title = "Purple tech texture"

[[generated]]
id = "OvBhqTDpEeZZpRpbMDe0W"
uri = "file://artifacts/mockup-sandbox/public/images/bg-tech-2.png"
type = "image"
title = "Dark neon tech texture"

[[outputs]]
id = "xIx3cuZKUd_S9iGpodKUW"
uri = "file://artifacts/vaultalk/public/vaultalk-logo.svg"
type = "image"
title = "Vaultalk Logo — Light / Transparent"

[[outputs]]
id = "7xtwyAalFWtdJlAAzNSyq"
uri = "file://artifacts/vaultalk/public/vaultalk-logo-dark.svg"
type = "image"
title = "Vaultalk Logo — Dark Background"
